#!/usr/bin/env escript
%% -*- erlang -*-
%%! -noshell -pa ebin -pa deps/mochiweb/ebin -pa deps/kvc/ebin

-include("../src/vindinium.hrl").

main([Key]) ->
    main([Key, ?MODE, ?TURNS, ?SERVER]);

main([Key, Mode]) ->
    main([Key, list_to_atom(Mode), ?TURNS, ?SERVER]);

main([Key, Mode, Turns]) ->
    main([Key, list_to_atom(Mode), list_to_integer(Turns), ?SERVER]);

main([Key, Mode, Turns, Url]) ->
    {ok, Context} = vindinium:connect(Key, Url, Mode, Turns),
    {ok, State} = vindinium:play(Context),
    io:format("~p~n", [vindinium_state:winner(State)]);

main(_Args) ->
    io:format("Usage: vindinium <secret-key> [<[training|arena]> [<turns>]]~n", []).
